apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-10-04T09:15:33Z"
    generation: 1
    labels:
      app: nginx-deploy
    name: nginx-deploy
    namespace: new-deploy
    resourceVersion: "81058"
    uid: 60757556-65ce-4702-a5fd-1cf4abf75872
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nginx-deploy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx-deploy
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-10-04T09:15:51Z"
      lastUpdateTime: "2024-10-04T09:15:51Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-10-04T09:15:33Z"
      lastUpdateTime: "2024-10-04T09:15:51Z"
      message: ReplicaSet "nginx-deploy-5fd7574f9f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-10-04T09:15:33Z"
    generation: 1
    labels:
      app: nginx-deploy
      pod-template-hash: 5fd7574f9f
    name: nginx-deploy-5fd7574f9f
    namespace: new-deploy
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: nginx-deploy
      uid: 60757556-65ce-4702-a5fd-1cf4abf75872
    resourceVersion: "81057"
    uid: d5df9110-acee-4b94-9614-5b44e52e6686
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx-deploy
        pod-template-hash: 5fd7574f9f
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx-deploy
          pod-template-hash: 5fd7574f9f
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
