#
# Управляет подами
#   запускает рабочую нагрузку.
# 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1 # под будет иметь эту метку?
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: registry.k8s.io/e2e-test-images/agnhost:2.39
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"

