apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-deployment
  labels:
    app: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: ksxack/lesson1:v0.2
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 8080