apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson1-4
  labels:
    app: goweb
spec:
  containers:
    - name: web
      image: ksxack/lesson1:v0.2 
      
      resources:
        limits:
          cpu: 500m
          memory: 256Mi

      ports:
        - name: web
          containerPort: 8080
          protocol: TCP