apiVersion: v1
kind: Service
metadata:
  name: my-balancer
  namespace: lesson1-4
spec:
  ports:
  - port: 80
    name: webport
    targetPort: 8080
  selector:
    app: goweb

  type: LoadBalancer # !!!
  loadBalancerIP: 10.10.130.145